### ISSUE TITLE
Apply Writing Checklist

### ISSUE THREAD

**Issue by katyhuff** [arfc/2020-fairhurst-hydrogen-production#3]
All documents should be reviewed in the context of the [writing checklist](http://arfc.github.io/manual/guides/writing/checklist/) before technical review. This issue can be closed when the writing checklist below has been applied to your document. 

- [x] Run a spell checker.
- [x] The Oxford comma must appears in lists ("lions, tigers, and bears.")
- [x] Do not use the word "where" unless referring to a location (try "such that" or "in which").
- [x] Do not use the word "when" unless referring to a time (try "if" instead).
- [x] Only use "large" when referring to size.
- [x] Use of "very" suggests that a cooler word exists.
- [x] Other misused/overused words include: code, input, output, different, value, amount, model.
- [x] Articles such as "a" "the" "some" "any" and "each" must appear where necessary.
- [x] All subjects match the plurality of their verbs ( no: "Apples is tasty" yes: "Apples are tasty")
- [x] Avoid run-on sentences.
- [x] clunky nouns -> spunky verbs (progression, expression --> progress, express)
- [x] reduce vague words (important, methodologic)
- [x] reduce acronyms / jargon
- [x] expand all acronyms on first use (rely on the acros.tex file and glossaries package to automate this)
- [x] get rid of unnecessary prepositional phrases -- author clearing throat (It can be shown that)
- [x] get rid of extraneous adverbs (very, really, quite, basically, generally)
- [x] get rid of there are / there is
- [x] turn negatives to positives (she was not often right -> she was usually wrong)
- [x] get rid of extraneous prepositions (the meeting happened on monday -> the meeting happened monday) (they agreed that it was true -> they agreed it was true)
- [x] get rid of passive voice (is/was/are/were/be/been/am + past tense verb), replace with active voice
- [x] use strong verbs (use sparingly: is, are, was, were, be, been, am)
- [x] avoid turning verbs into nouns ("obtain estimates of" -> "estimates"; "provides a description of" -> "describes") 
- [x] don't bury the verb (keep the predicate close to the subject at the beginning of the sentence)
- [x] data is plural (the data are critical)
- [x] compare to (point out similarities between different things) vs.  compared with (point out differences between similar things)
- [x] punctuation helps you to vary your sentence structure
- [x] Power to separate in increasing power: comma, colon, dash, parentheses, semicolon, period
- [x] In increasing order of formality: dash, parentheses, all of the others. Don't overdo it with the dash and parentheses
- [x] semicolon: connects two independent clauses. OR used to separate when the items in the list contain internal punctuation.
- [x] use a colon to introduce a list, quote, explanation, conclusion, or amplification
- [x] if there's a list in a sentence, it shouldn't come before the colon
- [x] use a dash to insert something in the middle of the sentence. Don't overuse it.
- [x] Always use isotopic notation like `$^{239}Pu$`. Never $Pu-239$ or plutonium-239. 
- [x] Elemental symbols (Ni, Li, Na, Pu) are capitalized, but their names are not (nickel, lithium, sodium, plutonium).
- [x] A phrase of the form `<verb>ion of <noun>` is probably clearer as `<noun> <verb>ion`. (For example, convert "calculation of velocity" to "velocity calculation".)
- [x] Cite all software. Review [the principles](https://www.force11.org/software-citation-principles) and try [CiteAs](https://citeas.org/about) if necessary. 
- [x] Refer to software consistently by name.

Additional Table and Figure Checklist:
- [x] The text should refer to all tables and figures.
- [x] When referring to figures by their number, use `Figure 1` and `Table 1.` They should be capitalized and not abbreviated (not `fig. 1` or `figure 1`.)
- [x] In tables, align all columns of numbers such that the decimals line up. 
- [x] In a single column, all values should probably have the same number of significant digits.
- [x] Give units for each numerical column.
- [x] A table should have only 3 horizontal lines (no vertical lines and no more than 3.)

Additional Math Comments:
- [x] define all variables, with units. If unitless, indicate that this is the case `$[-]$`.
- [x] subscripts should be brief and can be avoided with common notation. For example, `$\dot{m}$` is better than `$m_f$` which is superior to `$m_{flow}$`.
- [x] variable names should be symbols rather than words `m` is better than `mass` and `\ksi` is better than `one_time_use_variable`.
- [x] The notation $3.0\times10^12$ is preferred over $3e12$.
- [x] Equations should be part of a sentence.
- [x] Equations should be in the `align` environment. Align them at the `=` sign. 
- [x] Variables should be defined in the `align` environment as well, not buried in paragraphs.

```latex
The line is defined as 
\begin{align}
y&=mx + b
intertext{where}
y&= \mbox{ height of the line, also known as rise [m]}\nonumber\\
m&= \mbox{ slope [-]}\nonumber\\
x&=\mbox{ independent parameter, known as run [m]}\nonumber\\
b&= \mbox{ y intercept [m].}
\end{align}
```

**Comment by robfairh** [comment]
The writing checklist has been applied to my best ability.

**Comment by katyhuff** [comment]
I have reopened this issue because a few checklist items need more attention. 

- [x] Use a spellchecker.
"Acknowledgements" is currently misspelled.

- [x] Articles such as "a" "the" "some" "any" and "each" must appear where necessary.
"takes place in a unit called electrolyzer" should be "takes place in a unit called an electrolyzer"
"to fuel Champaign-Urbana Mass Transit District (MTD) bus system" should be "to fuel the Champaign-Urbana Mass Transit District (MTD) bus system"

- [x] turn negatives to positives (she was not often right -> she was usually wrong)
"will not be enough" could be "will be insufficient" 

- [x] Only use "large" when referring to size.
I recommend  "a large number of" should be replaced with "many." 

- [x] Other misused/overused words include: code, input, output, different, value, amount, model.

While "large amounts of" is not a terrible use of "large", this phrase violates another checklist item (this one.) Generally, specificity beats generality, so consider replacing "large amounts" with something more specific (in Table 2, you give a number for UIUC, so perhaps use that and report it in pounds or tonnes or CO2 per day or year.)

Similarly: 
- instead of "Table II lists the required amounts of hydrogen to supply the MTD fleet" I recommend "Table II lists the masses of hydrogen required to fuel the MTD fleet." 
- "the greatest amount of" could be "the most"
- "the amount of hydrogen required to fuel" could be "the mass of hydrogen required to fuel"
- "the amount of CO2 produced by both fleets." could be "the mass CO2 emitted by both fleets."


- [x]  Equations should be part of a sentence.
See equations 1 & 2, which deserve to have punctuation at the end of them. This requires that one add a period at the end of equation 1 and at the end of equation 2, because they are part of a sentence, and sentences end with periods. Also, consider rephrasing these sentences so that they read like actual sentences that truly include the equations. I recommend something like the following for both sentences:

```
The reaction is endothermic and requires the supply of heat to 
convert methane and water to carbon monoxide and hydrogen 
gas with the following balance equation [5],

CH4 +H2O+heat→CO+3H2 .         (1)
```

- [x] use strong verbs (use sparingly: is, are, was, were, be, been, am)

This paper retains quite a lot of these passive verbs where simple changes would strengthen the sentences... Search for these words and seek more powerful verb forms instead. While they typically cannot be eradicated, let's reduce their appearance. For example, instead of 

"Thus, it is necessary to decarbonize transportation. The \gls{UIUC} is doing its part by executing the Illinois Climate Action Plan (iCAP). The iCAP goal is to attain carbon neutrality by 2050 \cite{noauthor_illlinois_2015}." 

try:

"Thus, decarbonizing transportation underpins global carbon reduction. Accordingly, the \gls{UIUC} has committed to the Illinois Climate Action Plan (iCAP) which aims to attain carbon neutrality by 2050 \cite{noauthor_illlinois_2015}." 

Unrelated: Any citation with "noauthor" is missing some metadata. Please check the Zotero metadata and give all documents an author.

- [x] get rid of extraneous prepositions (the meeting happened on monday -> the meeting happened monday) (they agreed that it was true -> they agreed it was true)

"take into account the assumption that" could be "assume that" 
"Electrolysis is the process of using" could be "Electrolysis uses"
